sudo: true
dist: trusty
language: node_js
cache:
  directories:
  - node
  - node_modules
node_js:
  - 6.9
services:
  - mongodb
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - google-chrome-beta
before_install:
  - curl https://install.meteor.com | /bin/sh
  - npm install -g meteor-client-bundler
  - npm install
  - npm run meteor-client:bundle
  - ng build
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - ng test --watch false
  - ng test --code-coverage --single-run

after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
